# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

target 'Example' do
    project './Example.xcodeproj'
    workspace './Example.xcworkspace'

    pod 'MagicBell', :path => '../'
    pod 'ProgressHUD'
    pod 'SwiftLint'
end


