# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!

target 'Example' do
    project './Example.xcodeproj'
    workspace './MagicBell.xcworkspace'

    pod 'MagicBell', :path => '../'
    pod 'SwiftLint'

    target 'ExampleTests' do
        inherit! :search_paths
    end
end
