# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Resolves the dependences needed in MagicBell.xcodeproj"
  lane :init do
    carthage(
      command: "update",
      no_skip_current: false,
      use_xcframeworks: true,
      use_binaries: false,
    )
  end

  desc "Verifies the build process of MagicBell deployment"
  lane :build do
    carthage(
      command: "build",
      no_skip_current: false,
      use_xcframeworks: true,
      use_binaries: false,
    )
  end

  desc "Running MagicBell Tests in iPhone 13 Simulator"
  lane :tests do
    carthage(
      command: "update",
      no_skip_current: false,
      platform: "iOS",
      use_xcframeworks: true,
      use_binaries: false,
    )

    run_tests(
      project: "MagicBell.xcodeproj",
      scheme: "MagicBellTests",
      devices: ["iPhone 13"]
    )
  end
end

